workspace:
  aws:
    account_id: 654654531100
    role: ""
    profile: "yash"
    region: "us-east-1"
  common:
    environment: "dev"
    region_code : "eu1"
    tags:
      "Module": "VPC"
  vpc:
    cidr_block: "10.10.0.0/20"
    subnet:
      private:
        is_public: false
        nat_gateway: true
        details:
          - availability_zone: "a"
            cidr_address: "10.10.0.0/22"
          - availability_zone: "b"
            cidr_address: "10.10.4.0/22"
      public:
        is_public: true
        nat_gateway: false
        details:
          - availability_zone: "a"
            cidr_address: "10.10.12.0/24"
          - availability_zone: "b"
            cidr_address: "10.10.13.0/24"
      database:
        is_public: false
        nat_gateway: false
        details:
          - availability_zone: "a"
            cidr_address: "10.10.14.0/24"
          - availability_zone: "b"
            cidr_address: "10.10.15.0/24"
    create_vpc_endpoint: false
