workspace:
  aws:
    account_id: 654654531100
    role: ""
    profile: ""
    region: "us-east-1"
  common:
    environment: "dev"
    region_code : "ue1"
    tags:
      "Module": "EC2/ELB"

  security_group:
    public_sg:
      inbound:
        - from_port: 443
          to_port: 443
          protocol: "tcp"
          self: "false"
          cidr_blocks: ["182.71.160.184/29", "61.12.91.216/29"]
          description: "Allowing Office IPs"
        - from_port: 80
          to_port: 80
          protocol: "tcp"
          self: "false"
          cidr_blocks: ["182.71.160.184/29", "61.12.91.216/29"]
          description: "Allowing Office IPs"
                                                                                               
      outbound:
        - from_port: 0
          to_port: 0
          protocol: "-1"
          cidr_blocks: [ "0.0.0.0/0" ]
          description: "Allow HTTP traffic to internet"      

  ec2:
    load_balancer:
      - name: "public-alb"
        enable_deletion_protection: false
        is_private_load_balancer: false
        idle_timeout: 300
        load_balancer_type: "application"
        log_enable: false
        log_bucket_name: ""
        log_bucket_prefix: ""
        target_group_port: 80
        target_group_protocol: "HTTP"
        target_group_type: "instance"
        target_group_deregistration_delay: 30
        target_group_health_check_path: "/"
        listener_action_type: "forward"
        drop_invalid_header_fields: false
        http_listener_enable: true
        https_listener_enable: false
        http_listener_port: 80
        http_listener_protocol: "HTTP"
        https_listener_port: 443
        https_listener_protocol: "HTTPS"
